### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-science#1]
Updates for Homebrew-Science on Linuxbrew

**Comment by andreabedini** [comment]
@sjackman Please update us of #mozsprint about the updates you need to update :)

**Comment by sjackman** [comment]
Hi, Andrea! I've created issue #2 to track #mozsprint. cc @eronisko

**Comment by sjackman** [comment]
I've created issue #3 to track the progress of bottling bioinformatics software for Linuxbrew.
