### ISSUE TITLE
transdecoder: Transdecoder.Predict: cd-hit-est: No such file or directory

### ISSUE THREAD

**Issue by mestato** [Linuxbrew/homebrew-science#278]
### Indicate troubleshooting steps taken
- [ ] Ran `brew update` and retried your prior step?
  Yes, same error.
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
  Yes, same error.
- [ ] Checked that a similar issue hasn't already been filed?
  Nope, no transdecoder issues.
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:
- Brief summary of issue:
  When running Transdecoder.Predict, it can't find cd-hit-est, a dependency software. Full error:

```
Can't exec "../Cellar/cd-hit/4.6.6/bin/cd-hit-est": No such file or directory at /home/linuxbrew/.linuxbrew/bin/TransDecoder.Predict line 339.
Error, cmd: ../Cellar/cd-hit/4.6.6/bin/cd-hit-est -r 1 -i cdna_nointrons_utrs.fa.transdecoder_dir/longest_orfs.cds.top_longest_5000 -T 1 -c 0.80 -o cdna_nointrons_utrs.fa.transdecoder_dir/longest_orfs.cds.top_longest_5000.nr80 -M 0  died with ret -1 at /home/linuxbrew/.linuxbrew/bin/TransDecoder.Predict line 342.
```

Background:
The brew formula removes the plugins for transdecoder and installs cd-hit-est separately, but then Transdecoder looks for it using a relative path and can't find it.

Please state the complete command that you issued.

```
TransDecoder.Predict -t cdna_nointrons_utrs.fa --retain_pfam_hits cdna_nointrons_utrs.fa.transdecoder_dir/longest_orfs.pep.pfam.tbl --retain_long_orfs 600
```

**Comment by sjackman** [comment]
Torsten @tseemann is making progress on this issue.
https://github.com/TransDecoder/TransDecoder/issues/26

**Comment by sjackman** [comment]
I believe that this issue has been resolved.
