### ISSUE TITLE
Update bottles for Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/homebrew-science#279]
- [x] abyss
- [ ] afra
- [ ] analysis
- [ ] andi
- [ ] art
- [ ] bless
- [ ] breseq
- [ ] clark
- [ ] clonehd
- [ ] dextractor
- [ ] diamond
- [ ] diamond
- [ ] dida
- [ ] express
- [ ] fwdpp
- [ ] fwdpp
- [ ] garli
- [ ] harvest-tools
- [ ] igv
- [ ] igvtools
- [ ] iqtree
- [ ] jellyfish-1.1
- [ ] kallisto
- [ ] kmacs
- [ ] lobstr
- [ ] lsd
- [ ] macse
- [ ] mash
- [ ] mash
- [ ] meme
- [ ] nanopolish
- [ ] nextflow
- [ ] pathvisio
- [ ] plink
- [ ] poretools
- [ ] proteinortho
- [ ] quaff
- [ ] rapsearch2
- [ ] ray
- [x] salmon
- [ ] sambamba
- [ ] sdsl-lite
- [ ] sequel
- [ ] spaced
- [ ] sratoolkit
- [ ] stringtie
- [ ] swarm
- [ ] tabtk
- [ ] vsearch
- [ ] vt

**Comment by harryjubb** [comment]
Any news on this? Struggling at the `glew` install stage for PyMOL, if that is included.

**Comment by sjackman** [comment]
I've opened a PR to build a bottle for `pymol` over at https://github.com/Homebrew/homebrew-science/pull/5102
