### ISSUE TITLE
sga failed to build on CentOS 6.7

### ISSUE THREAD

**Issue by vsuryaw** [Linuxbrew/homebrew-science#281]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
  A similar issue was filed in 2014- [link](https://github.com/Homebrew/homebrew-science/issues/555) , I tried the steps recommended there, but it did not work
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:
- Brief summary of issue: **Latest sga formula fails to build**
- Please state the complete command that you issued : `brew install sga`
- [gist](https://gist.github.com/anonymous/238a0b79d30ef8b24b31b1cf7865d7dc)

I initially tried to upgrade the sga formula from version 0.10.13 to the latest 0.10.14. When that didn't work, I removed bamtools, google-sparsehash and tried again, as suggested in one of the troubleshooting threads before - [link](https://github.com/Homebrew/homebrew-science/issues/555) . 

Thereafter, I removed my older version of sga, and tried a fresh reinstall of latest version. This still fails. I have attached the gist of the same above.

**Comment by sjackman** [comment]
I'm heading out of town for the long weekend. As a workaround, you can install Linuxbrew in `/home/linuxbrew/.linuxbrew` to use the precompiled bottle of `sga`. You can also try `brew install --force-bottle sga` with your current installation, which _may_ work, but no guarantee.

**Comment by vsuryaw** [comment]
Thanks, the --force-bottle option worked.

**Comment by sjackman** [comment]
Glad to hear it, @aviantask.

@jts The precompiled binary bottle of `sga` is marked as non-relocatable (after it's compiled and installed in a given location, it can't be moved from that location). I'd like to look into why that is, so that the bottle can be properly marked as relocatable (`cellar :any`). (More of a reminder to myself.)
